[profile.default]
src = 'contracts'
out = 'out'
solc_version = '0.8.19'
optimizer_runs = 1000000
via_ir = false
libs = ['node_modules', 'lib', 'contracts/libraries']
test = 'test'
cache_path  = 'foundry-cache'
gas_reports = ["Arbiter"]
bytecode_hash = "none"
ffi = false

[fuzz]
runs = 1000

[invariant]
runs = 5